# Generated by Django 3.0.8 on 2020-07-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieBoard', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='address',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
