# Generated by Django 3.0.8 on 2020-07-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieBoard', '0003_movie_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='explain',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
